config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if params[:id] == ""
  		@nothing = "Please enter something!"
  	elsif 
  		if params[:id]
  			begin
  				@stock = StockQuote::Stock.quote(params[:id])
  			rescue StandardError
  				@error = "Invalid Company Ticker Symbol"
  			end
  			@stock = StockQuote::Stock.quote(params[:id])
  		end
  	end
  end

  def about
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end

    def correct_user
      @ticker = current_user.stocks.find_by(id: params[:id])
      redirect_to stocks_path, notice: "Not authorized to edit this stock" if @ticker.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
	<div class="alert alert-warning alert-dismissible">
		<button class="close" data-dismiss="alert"><
			<i class="glyphicon glyphicon-remove-circle"></i>
		</button>
		<%= content_tag(:div, msg) %>
	</div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Stock</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "About Us", home_about_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav navbar-right">

    	<% if user_signed_in? %>
    		<li><%= link_to "List Stocks", stocks_path, class: 'nav-link' %></li>
    		<li><%= link_to "Add Stock", new_stock_path, class: 'nav-link' %></li>
    		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
    		<li><%= link_to "Edit User", edit_user_registration_path, class: 'nav-link' %></li>
    	<% else %>
    		<li><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
    		<li><%= link_to "Log In", new_user_session_path, class: 'nav-link' %></li>
    	<% end %>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>This app displays the searched ticker of a company's stocks info. It will allow users to save the stocks that they want. They can edit or delete the stock of their list.</p>

app/views/home/index.html.erb
<h1>Stock Search</h1>
<br/><br/>
<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag 'id', nil, placeholder: "Enter Company Ticker Symbol", size: 50, class: "form-control" %>
	<br/><br/>
	<%= submit_tag 'Search', class: "btn btn-outline-primary" %>
<% end %>

<br/><br/>

<% if @stock %>
	<strong>Company Name: </strong><%= @stock.company_name %> - <%= @stock.symbol %><br/>
	<strong>Lastest Price: </strong><%= @stock.latest_price %><br/>
	<strong>Market Cap: </strong><%= @stock.market_cap %><br/>
	<strong>Price/Earning Ratio: </strong><%= @stock.pe_ratio %><br/>
	<strong>Close Price: </strong><%= @stock.close %><br/>
	<strong>Stock Open: </strong><%= @stock.open %><br/>
	<strong>Change Percent: </strong><%= @stock.change_percent %><br/>
	<strong>High: </strong><%= @stock.high %><br/>
	<strong>Low: </strong><%= @stock.low %><br/>

<% elsif @nothing %>
	<%= @nothing %>
<% end %>

<% if @error %>
	<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  	<%= render 'home/navbar' %>
  	<div class="container">
  		<% render 'home/flash' %>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, id: :stock_ticker, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>My Stocks</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Company Name</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Company Worth</th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
        <% if stock.user_id == current_user.id %>
            <% begin %>
              <% @stock_quote = StockQuote::Stock.quote(stock.ticker) %>
            <% rescue StandardError %>
              <tr>
                <td><%= link_to 'N/A', stock %></td>
                <td><%= stock.ticker %></td>
                <td><%= 'Error' %></td>
                <td><%= 'Error' %></td>
              </tr>
              <% next %>
            <% end %>

            <tr>
              <td><%= link_to @stock_quote.company_name, stock %></td>
              <td><%= stock.ticker %></td>
              <td><%= @stock_quote.latest_price %></td>
              <td><%= @stock_quote.market_cap %></td>
            </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path, class: 'btn btn-outline-primary' %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Return', stocks_path, class: "btn btn-outline-danger" %>

app/views/stocks/show.html.erb
<% begin %>
    <% @stock_quote = StockQuote::Stock.quote(@stock.ticker) %>
<% rescue StandardError %>
    <% 'Invalid Company' %>         
<% end %>

<div class="jumbotron">
	<h1 class="display-4"><%= @stock_quote.company_name %></h1><br/>
	<p class="lead">$<%= @stock_quote.latest_price %></p><br/>
	<hr class="my-4">
	<strong>Market Cap: </strong>$<%= @stock_quote.market_cap %><br/>
	<strong>Price/Earning Ratio: </strong>$<%= @stock_quote.pe_ratio %><br/>
	<strong>Close Price: </strong>$<%= @stock_quote.close %><br/>
	<strong>Stock Open: </strong>$<%= @stock_quote.open %><br/>
	<strong>Change Percent: </strong><%= @stock_quote.change_percent %>%<br/>
	<strong>High: </strong>$<%= @stock_quote.high %><br/>
	<strong>Low: </strong>$<%= @stock_quote.low %><br/>
</div>

<br/><br/>
<%= link_to 'Edit', edit_stock_path(@stock), class: 'btn btn-outline-secondary' %>
<%= link_to 'Delete', stock_path(@stock), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-warning" %>
<%= link_to 'Return', stocks_path, class: 'btn btn-outline-danger' %>